#!/bin/bash
clear
source msg
change_port(){
unset var
var="$1"
	cat >> /etc/nginx/sites-available/default <<- eof
		##
		# You should look at the following URL's in order to grasp a solid understanding
		# of Nginx configuration files in order to fully unleash the power of Nginx.
		# https://www.nginx.com/resources/wiki/start/
		# https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/
		# https://wiki.debian.org/Nginx/DirectoryStructure
		#
		# In most cases, administrators will remove this file from sites-enabled/ and
		# leave it as reference inside of sites-available where it will continue to be
		# updated by the nginx packaging team.
		#
		# This file will automatically load configuration files provided by other
		# applications, such as Drupal or Wordpress. These applications will be made
		# available underneath a path with that package name, such as /drupal8.
		#
		# Please see /usr/share/doc/nginx-doc/examples/ for more detailed examples.
		##

		# Default server configuration
		#
		server {
			listen $1 default_server;
			listen [::]:$1 default_server;

			# SSL configuration
			#
			# listen 443 ssl default_server;
			# listen [::]:443 ssl default_server;
			#
			# Note: You should disable gzip for SSL traffic.
			# See: https://bugs.debian.org/773332
			#
			# Read up on ssl_ciphers to ensure a secure configuration.
			# See: https://bugs.debian.org/765782
			#
			# Self signed certs generated by the ssl-cert package
			# Don't use them in a production server!
			#
			# include snippets/snakeoil.conf;

			root /var/www/html;

			# Add index.php to the list if you are using PHP
			index index.html index.htm index.nginx-debian.html;

			server_name _;

			location / {
				# First attempt to serve request as file, then
				# as directory, then fall back to displaying a 404.
				try_files \$uri \$uri/ =404;
			}

			# pass PHP scripts to FastCGI server
			#
			#location ~ \.php$ {
			#	include snippets/fastcgi-php.conf;
			#
			#	# With php-fpm (or other unix sockets):
			#	fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
			#	# With php-cgi (or other tcp sockets):
			#	fastcgi_pass 127.0.0.1:9000;
			#}
			# deny access to .htaccess files, if Apache's document root
			# concurs with nginx's one
			#
			#location ~ /\.ht {
			#	deny all;
			#}
		}


		# Virtual Host configuration for example.com
		#
		# You can move that to a different file under sites-available/ and symlink that
		# to sites-enabled/ to enable it.
		#
		#server {
		#	listen 80;
		#	listen [::]:80;
		#
		#	server_name example.com;
		#
		#	root /var/www/example.com;
		#	index index.html;
		#
		#	location / {
		#		try_files $uri $uri/ =404;
		#	}
		#}

	eof
	#rm -f /etc/nginx/sites-enabled/default &> /dev/null
	#ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
	systemctl daemon-reload
	systemctl restart nginx
}

nginxport=$(lsof -V -i tcp -P -n | grep -v "ESTABLISHED" |grep -v "COMMAND" |grep "nginx"|awk '{print $9}'|awk -F ":" '{print $2}')
tittle
if [[ -z $nginxport ]]; then
	menu_func 'INSTALAR NGINX'
	back
	case `selection_fun 1` in
	 1)msg -ama 'INSTALANDO NGINX'
		fun_bar 'apt-get install nginx'
		wget -O /etc/nginx/nginx.conf https://gitea.com/drowkid01/scriptdk1/raw/branch/main/Recursos/menu/nginx.conf &> /dev/null
		wget -O /etc/nginx/conf.d/vps.conf https://gitea.com/drowkid01/scriptdk1/raw/branch/main/Recursos/menu/vps.conf &> /dev/null
		/etc/init.d/nginx restart &> /dev/null
		nginx &> /dev/null		;;
	 0)return $?;;
	esac
enter
else
	echo -e "$(printext 'PUERTO NGINX:') \e[1;97m$(lsof -V -i tcp -P -n | grep -v "ESTABLISHED" |grep -v "COMMAND" |grep "nginx"|awk '{print $9}'|awk -F ":" '{print $2}'|xargs)"
	menu_func 'EDITAR PUERTO NGINX' '-vm DESINSTALAR NGINX'
	back
	case `selection_fun 2` in
	 1)read -p $'\e[1;31mingrese el nuevo puerto para nginx: ' ngi
		[[ -z $ngi ]] && return $? || {
			nport=$(lsof -V -i tcp -P -n | grep -v "ESTABLISHED" |grep -v "COMMAND" |grep "nginx"|awk '{print $9}'|awk -F ":" '{print $2}')
			if systemctl stop nginx ; then
				change_port "$ngi"
			fi
		}
	 ;;
	 2)
	msg -ama 'DESINSTALANDO NGINX'
		systemctl stop nginx
		systemctl disable nginx
		systemctl daemon-reload
		apt purge nginx
		apt autoremove
		apt clean
		killall nginx
	;;
	esac
enter
fi


